version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node -v && npm -v
            - run: npm install
            - run: npm build
            - run: sudo apt-get install rsync && rsync --version
            - run: ls
            - run: rsync -a -e "ssh -o StrictHostKeyChecking=no" src/ centos@54.82.112.85:~/nodedeploy/
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only: master # only deploy on the master branch